#include <gtk/gtk.h>
void precess (double, double, double *, double *, double, double);
double tosecs (int, int, int, int, int);
void radec_azel (double, double, double, double *, double *);
void GalactictoRadec (double, double, double *, double *);
double vlsr (double, double, double);
void toyrday (double, int *, int *, int *, int *, int *);
char *to_date (int, int);
char *to_radecp (double, double);
double gst (double);
void sunradec (double, double *, double *);
void moonradec (double, double *, double *);
void polyfitr(int,int,float*,float*,float*);
void  MatrixInvert(int,long double*,long double*);
int dayofyear (int, int, int);
void plotbox (void);
int catfile (void);
void setsounam (void);
void galactp (void);
double readclock (void);
void plotspec (int);
void plotp (double);
void azel (double, double);
void cal (int);
void azel_to_radec (double, double, double, double *, double *);
void outfile (void);
void Four (double *, double *, int);
double cmdfile (void);
void zerospectra (int);
void aver (void);
double gauss(void);
gint Repaint (void);
void cleararea (void);
void quit (void);
void vquit (void);
gint expose_event (GtkWidget *, GdkEventExpose *);
gint configure_event (GtkWidget *);
gint vexpose_event (GtkWidget *, GdkEventExpose *);
gint vconfigure_event (GtkWidget *);
void button_clear_clicked (void);
void button_psw_clicked (void);
void button_stow_clicked (void);
void button_mode_clicked (void);
void button_azel_clicked (void);
void button_npoint_clicked (void);
void button_bsw_clicked (void);
void button_freq_clicked (void);
void button_offset_clicked (void);
void button_record_clicked (void);
void button_cmdfl_clicked (void);
void button_cal_clicked (void);
void button_help_clicked (void);
void button_exit_clicked (void);
void hit_enter_azel (void);
void hit_enter_record (void);
void hit_enter_freq (void);
void hit_enter_cal (void);
void hit_enter_offset (void);
void hit_enter_cmdfl (void);
gint button_press_event (GtkWidget *,GdkEventButton *);

void clearpaint (void);
void vclearpaint (void);
void find_d1 (char **, char **, int *);
void scanplot(void);
double cmdfile(void);
char *kmatch(char *,char *);

void display_help(void);
void record_tooltip(void);
void mode_tooltip(void);
void velspec(void);
void vplot(void);
void vspectra(void);
int rot2(double*,double*,int,char*);
void Init_Device(int);
